### ISSUE TITLE
error while scrapping blackbox exporter endpoint

### ISSUE THREAD

**Issue by ilyesAj** [wrouesnel/reverse_exporter#3]
i'm having an error when scraping a blackbox exporter endpoint . 

here is the config on reverse_exporter: 
```yml
- path: /metrics
  exporters:
  - http:
      name: authent
      address: http://blackbox:9115/probe?target=prometheus.io&module=http_2xx
      timeout: 1s
      labels:
        metrics_type: healthCheck
```
i'm launching blackbox and reverse exporter on a docker-compose : 
```yml
version: '2'

services:
  reverse-exporter:
    image: reverse_exporter:0.3
    ports:
    - 9998:9998
    volumes:
    - ./test.yaml:/etc/reverse_exporter/config.yml
  blackbox:
    image: prom/blackbox-exporter:master
    ports:
    - 9115:9115
    volumes:
    - /home/ilyes/sandbox:/config
    command: --config.file=/config/blackbox.yml
```
log :
```log
Error while scraping backend handler for endpoint" error="server returned HTTP status 400 Bad Request" source="reverse_proxy.go:49"
```
